In [ ]:
#Numpy
#1d array
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)

In [ ]:
#2d array
import numpy as np
a=np.array([[2,3,4,5],[6,7,8,10]])
print(a)

In [ ]:
#Dimensions
import numpy as np
a=np.array(26)
b=np.array([18,28,33])
c=np.array([[36,12,24],[5,25,40]])
d=np.array([[[34,56,65],[45,39,15],[63,98,22]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

In [ ]:
#Array elements
import numpy as np
e=np.array([15,30,14,99])
print(e[2])

In [ ]:
#Add elements
import numpy as np
d=([25,4,8,6])
print(d[0]+d[3])

In [ ]:
#Attributes
d=np.array([[[34,56,65],[45,39,15],[63,98,22]]])
print(d.shape)
print(d.ndim)
print(d.size)
print(d.dtype)

In [1]:
#Slicing
import numpy as np
marks = np.array([
    [85, 90, 78],
    [88, 76, 92],
    [90, 85, 80],
    [70, 95, 88]
])
print(marks)


[[85 90 78]
 [88 76 92]
 [90 85 80]
 [70 95 88]]


In [2]:
print(marks[0,:])

[85 90 78]


In [4]:
print(marks[0:,0])

[85 88 90 70]


In [5]:
print(marks[2:4,2:])

[[80]
 [88]]


In [8]:
import numpy as np
marks = np.array([
    [85, 90, 78],
    [88, 76, 92],
    [90, 85, 80],
    [70, 95, 88]
])
print(marks[0:,:2])

[[85 90]
 [88 76]
 [90 85]
 [70 95]]


In [9]:
#first 3 studs last 2 subs
print(marks[0:3,1:3])

[[90 78]
 [76 92]
 [85 80]]


In [10]:
#Reshape
print(marks.shape)

(4, 3)


In [12]:
#Reshape into 2rows and 6 columns
reshaped1=marks.reshape(2,6)
print(reshaped1)

[[85 90 78 88 76 92]
 [90 85 80 70 95 88]]


In [13]:
#Reshape into 3d
reshaped2=marks.reshape(2,2,3)
print(reshaped2)

[[[85 90 78]
  [88 76 92]]

 [[90 85 80]
  [70 95 88]]]


In [14]:
#Using -1
reshaped3=marks.reshape(3,-1)
print(reshaped3)

[[85 90 78 88]
 [76 92 90 85]
 [80 70 95 88]]


In [15]:
reshaped4=marks.reshape(-1,2)
print(reshaped4)

[[85 90]
 [78 88]
 [76 92]
 [90 85]
 [80 70]
 [95 88]]


In [16]:
#Flatten()
print(marks)
print('shape:',marks.shape)

[[85 90 78]
 [88 76 92]
 [90 85 80]
 [70 95 88]]
shape: (4, 3)


In [18]:
flat=marks.flatten()
print('flatten:',flat)

flatten: [85 90 78 88 76 92 90 85 80 70 95 88]


In [21]:
#Ravel()
rav=marks.ravel()
print('ravel:',rav)

ravel: [85 90 78 88 76 92 90 85 80 70 95 88]


In [23]:
#Difference check
rav[0]=100
print('Ravel after change:',rav)
print('Original after ravel change:\n',marks)
flat[1]=99
print('Flatten after change:',flat)
print('Original after flatten change:\n',marks)

Ravel after change: [100  90  78  88  76  92  90  85  80  70  95  88]
Original after ravel change:
 [[100  90  78]
 [ 88  76  92]
 [ 90  85  80]
 [ 70  95  88]]
Flatten after change: [85 99 78 88 76 92 90 85 80 70 95 88]
Original after flatten change:
 [[100  90  78]
 [ 88  76  92]
 [ 90  85  80]
 [ 70  95  88]]


In [24]:
import numpy as np
a=np.array([10,20,30])
b=np.array([1,2,3])
print('a:',a)
print('b:',b)

a: [10 20 30]
b: [1 2 3]


In [25]:
print(a+b)

[11 22 33]


In [26]:
print(a-b)

[ 9 18 27]


In [27]:
print(a*b)

[10 40 90]


In [28]:
print(a**b)

[   10   400 27000]


In [29]:
print(a%b)

[0 0 0]


In [30]:
print(a/b)

[10. 10. 10.]


In [31]:
print(marks.shape)

(4, 3)


In [32]:
print(marks)

[[100  90  78]
 [ 88  76  92]
 [ 90  85  80]
 [ 70  95  88]]


In [33]:
print(marks+5)

[[105  95  83]
 [ 93  81  97]
 [ 95  90  85]
 [ 75 100  93]]


In [34]:
#Broadcasting
bonus=np.array([2,3,4])
print(marks+bonus)

[[102  93  82]
 [ 90  79  96]
 [ 92  88  84]
 [ 72  98  92]]


In [35]:
student_bonus=np.array([[5],[10],[6],[4]])
print(marks+student_bonus)

[[105  95  83]
 [ 98  86 102]
 [ 96  91  86]
 [ 74  99  92]]


In [5]:
import numpy as np
marks = np.array([
    [85, 90, 78],
    [88, 76, 92],
    [90, 85, 80],
    [70, 95, 88]
])
print('total sum:',np.sum(marks))
print('mean:',np.mean(marks))
print('min:',np.min(marks))
print('max:',np.max(marks))
print('median:',np.median(marks))
print('std dev:',np.std(marks))
print('variance:',np.var(marks))
print('row-wise sum:',np.sum(marks,axis=1))
print('column-wise sum:',np.sum(marks,axis=0))



total sum: 1017
mean: 84.75
min: 70
max: 95
median: 86.5
std dev: 7.048936089935842
variance: 49.6875
row-wise sum: [253 256 255 253]
column-wise sum: [333 346 338]


In [6]:
#Linear algebra
#1.Dot product
import numpy as np
m1=([1,2,3])
m2=([4,5,6])
print('dot product:',np.dot(m1,m2))

dot product: 32


In [14]:
#2.Matrix multiplication
m3=([
    [1,2],
    [3,4]
])
m4=([
    [5,6],
    [7,8]
])
print('matrix multiplication:\n',np.matmul(m3,m4))
print('determinant:',np.linalg.det(m3))
print('inverse:',np.linalg.inv(m3))

matrix multiplication:
 [[19 22]
 [43 50]]
determinant: -2.0000000000000004
inverse: [[-2.   1. ]
 [ 1.5 -0.5]]


In [18]:
#Sorting
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print(np.sort(unsorted))
print(np.argsort(unsorted))
print(np.where(unsorted > 3))



[1 1 2 3 4 5 6 9]
[1 3 6 0 2 4 7 5]
(array([2, 4, 5, 7]),)
